# Generated by Django 5.2.13 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.IntegerField(
                choices=[(1, 'Activo'), (0, 'Inactivo')],
                default=1,
            ),
        ),
    ]
